### ISSUE TITLE
right-aligned text in table

### ISSUE THREAD

**Issue by lugino-emeritus** [it-gro/hugo-theme-w3css-basic#160]
Would it be possible to support right-aligned text in tables? It does not work at the moment with this theme.

Example:
```
| Right | Center | Left |
| -----:|:------:|:---- |
|     1 |   2    | 3    |
```
should look like

| Right | Center | Left |
| -----:|:------:|:---- |
|     1 |    2   | 3    |

**Comment by it-gro** [comment]
Oh, thx.
That was a good one!
Fixed:

| Right | Center | Left |
| -----:|:------:|:---- |
|     1 |   2    | 3    |

| default | is left
| --------|--------
|    42   |   foo

Example in:
https://it-gro.github.io/hugo-theme-w3css-basic.github.io/faq/#6-praesent-fermentum-tempor

=>  static/css/w3css-basic.css 
td,th{padding:2px 8px;display:table-cell;vertical-align:top}
removed: text-align:left;

Thx for pointing it out
