### ISSUE TITLE
[params.blog] and starting page

### ISSUE THREAD

**Issue by icf20** [it-gro/hugo-theme-w3css-basic#291]
```
baseURL       = "http://example.com"
theme         = "hugo-theme-w3css-basic"
defaultContentLanguage = "es"
[taxonomies]
  tag      = "tags"


[params.blog]
  # used in layouts/blog/list.html
  title    = "Blog"
  icon     = "fas fa-rss"
  subtitle = '''
ultricies eget, tempor sit amet, ante
             '''
```

![image](https://user-images.githubusercontent.com/17784575/50231520-47c89a80-03af-11e9-9963-7e586e0b2d44.png)

expectation: have http://localhost:1313/blog/ content on http://localhost:1313/

**Comment by it-gro** [comment]
expectation: rtm

add:
```
[[menu.main]]
  name   = "Blog"
  url    = "/blog"
  pre    = "fas fa-rss"

[params.recentPosts]
  enableFront    = true
  title    = "From our Blog"
  subtitle = '''
Pellentesque habitant morbi tristique senectus et netus et malesuada
fames ac.
             '''
```

=> http://localhost:1313/
![tmp-002](https://user-images.githubusercontent.com/13005925/63554605-58cd3b00-c53e-11e9-99f0-a872654bcc4c.png)

http://localhost:1313/blog/ 
![tmp-003](https://user-images.githubusercontent.com/13005925/63554639-726e8280-c53e-11e9-83ff-7be3d0eb8e1b.png)

So this theme does have a front page, which is not the blog section ...
