### ISSUE TITLE
Site.RSSLink outdated in head.rss.html

### ISSUE THREAD

**Issue by onnotasler** [it-gro/hugo-theme-w3css-basic#297]
If I try to compile the theme, Hugo shows a warning the Site.RSSLink is outdated. It is referenced once in head.rss.html:

{{- if .Site.RSSLink }}
<link href='{{ .Site.RSSLink }}' rel="alternate" type="application/rss+xml" title='{{ .Site.Title }} (rss+xml alternate)' />
{{- end -}}

According to the Hugo documentation, it needs to be replaced with:
{{ with .OutputFormats.Get "rss" -}}
  {{ printf `<link rel=%q type=%q href=%q title=%q>` .Rel .MediaType.Type .Permalink site.Title | safeHTML }}
{{- end -}}

**Comment by it-gro** [comment]
Hi
Thanks for pointing this out - and even providing the fix.
Done in 00d02f0
